from typing import Protocol


class UsernameSyncCache(Protocol):
    async def get(self, telegram_id: int) -> str | None: ...

    async def set(self, telegram_id: int, value: str, ttl_seconds: int) -> None: ...


class ActiveCategoryStore(Protocol):
    async def get(self, telegram_id: int) -> str | None: ...

    async def set(self, telegram_id: int, category_code: str) -> None: ...


class CurrentMessageStore(Protocol):
    async def get(self, telegram_id: int) -> int | None: ...

    async def set(self, telegram_id: int, message_id: int) -> None: ...

    async def delete(self, telegram_id: int) -> None: ...


class ViewedAvailableOrdersStore(Protocol):
    async def list_viewed(self, telegram_id: int) -> set[str]: ...

    async def mark_viewed(self, telegram_id: int, order_id: str) -> None: ...
