from collections.abc import Callable
from dataclasses import dataclass
from datetime import timedelta
from decimal import Decimal, InvalidOperation
from typing import TYPE_CHECKING, Any, cast
from uuid import UUID

from backend.common.application import to_utc, utc_now
from backend.common.domain import (
    AuthorizationError,
    ConflictError,
    NotFoundError,
    ValidationError,
)
from backend.common.infrastructure import S3ObjectStorage
from backend.common.infrastructure.database import SqlAlchemyUnitOfWork
from backend.modules.addresses.application import (
    CreateCustomerAddressUseCase,
    CreateOwnerAddressCommand,
    CreatePerformerAddressUseCase,
    DeleteCustomerAddressUseCase,
    DeletePerformerAddressUseCase,
    SetPerformerCurrentAddressUseCase,
    SuggestAddressCommand,
    SuggestAddressesUseCase,
    UpdateCustomerAddressCommand,
    UpdateCustomerAddressUseCase,
)
from backend.modules.addresses.infrastructure import SqlAlchemyAddressRepository
from backend.modules.admin.application import (
    BootstrapAdminCommand,
    BootstrapAdminUseCase,
    GetCurrentAdminUseCase,
    LoginAdminCommand,
    LoginAdminUseCase,
    LogoutAdminUseCase,
)
from backend.modules.admin.infrastructure import (
    AdminAuditLogModel,
    Argon2PasswordHasher,
    RedisAdminSessionStore,
    SqlAlchemyAdminAuditRepository,
    SqlAlchemyAdminRepository,
)
from backend.modules.admin.presentation.api.schemas import BusinessSettingResponse
from backend.modules.availability.application import (
    AddCalendarOverrideCommand,
    AddCalendarOverrideUseCase,
    CheckPerformerAvailabilityCommand,
    CheckPerformerAvailabilityUseCase,
    FindSuitablePerformersCommand,
    FindSuitablePerformersUseCase,
    GetPerformerCalendarUseCase,
    SetPerformerScheduleCommand,
    SetPerformerScheduleUseCase,
)
from backend.modules.availability.infrastructure import SqlAlchemyAvailabilityRepository
from backend.modules.care_objects.application import (
    CreateCustomerCareObjectCommand,
    CreateCustomerCareObjectUseCase,
    DeleteCustomerCareObjectUseCase,
    ListCustomerCareObjectsUseCase,
    UpdateCustomerCareObjectCommand,
    UpdateCustomerCareObjectUseCase,
)
from backend.modules.care_objects.infrastructure import SqlAlchemyCareObjectRepository
from backend.modules.catalog.infrastructure import (
    SqlAlchemyBusinessSettingRepository,
    SqlAlchemyCatalogQueryService,
)
from backend.modules.customers.application import (
    GetCustomerProfileUseCase,
    RegisterCustomerCommand,
    RegisterCustomerUseCase,
    UpdateCustomerProfileCommand,
    UpdateCustomerProfileUseCase,
    UpdateCustomerUsernameCommand,
    UpdateCustomerUsernameUseCase,
)
from backend.modules.customers.infrastructure import (
    CustomerModel,
    SqlAlchemyCustomerRepository,
)
from backend.modules.files.application import (
    UploadPerformerAvatarCommand,
    UploadPerformerAvatarUseCase,
)
from backend.modules.files.infrastructure import SqlAlchemyFileRepository
from backend.modules.geo.infrastructure import DaDataGeocoder
from backend.modules.notifications.infrastructure import (
    NotificationModel,
    SqlAlchemyNotificationRepository,
)
from backend.modules.orders.application import (
    CalculatePricePreviewCommand,
    CalculatePricePreviewUseCase,
    CancelOrderCommand,
    CancelOrderUseCase,
    ConfirmReportCommand,
    ConfirmReportUseCase,
    CreateDirectOrderCommand,
    CreateDirectOrderUseCase,
    CreatePoolOrderCommand,
    CreatePoolOrderUseCase,
    FinishOrderCommand,
    FinishOrderUseCase,
    OrderReportDetailDTO,
    OrderReportFileDTO,
    StartOrderByCustomerCommand,
    StartOrderByCustomerUseCase,
    StartOrderCommand,
    StartOrderUseCase,
    SubmitOrderReportCommand,
    SubmitOrderReportUseCase,
)
from backend.modules.orders.infrastructure import (
    SqlAlchemyMatchingRepository,
    SqlAlchemyMyOrdersQueryService,
    SqlAlchemyOrderRepository,
    SqlAlchemyPricingRepository,
)
from backend.modules.payments.application import (
    ApplyPaymentWebhookUseCase,
    CreateManualRefundCommand,
    CreateManualRefundUseCase,
    GetCustomerPaymentStatusCommand,
    GetCustomerPaymentStatusUseCase,
    PaymentGatewayInitCommand,
    PaymentGatewayRefundCommand,
    PaymentWebhookCommand,
    RetryPaymentOperationCommand,
    RetryPaymentOperationUseCase,
)
from backend.modules.payments.infrastructure import (
    SqlAlchemyPaymentRepository,
    TBankPaymentGateway,
    TBankReceiptSettings,
)
from backend.modules.performers.application import (
    ActivatePerformerUseCase,
    ApprovePerformerServiceCommand,
    ApprovePerformerServiceUseCase,
    CreateInvitationCommand,
    CreateInvitationUseCase,
    GetRegistrationStateUseCase,
    ListPerformerServicesUseCase,
    RegisterPerformerCommand,
    RegisterPerformerUseCase,
    SetPerformerAcceptingOrdersCommand,
    SetPerformerAcceptingOrdersUseCase,
    SetPerformerServiceEnabledCommand,
    SetPerformerServiceEnabledUseCase,
    SetPerformerServiceMaxObjectsCommand,
    SetPerformerServiceMaxObjectsUseCase,
    UpdatePerformerUsernameCommand,
    UpdatePerformerUsernameUseCase,
)
from backend.modules.performers.infrastructure import (
    PerformerModel,
    SqlAlchemyPerformerRepository,
)
from backend.modules.support.infrastructure import (
    AccountDeletionRequestModel,
    ComplaintModel,
    ContactRequestModel,
    DisputeModel,
    SqlAlchemySupportRepository,
    SupportRequestModel,
)
from backend.modules.system_checks.application import (
    CreateSystemCheckCommand,
    CreateSystemCheckUseCase,
)

__all__ = [
    "AccountDeletionRequestModel",
    "ActivatePerformerUseCase",
    "AddCalendarOverrideCommand",
    "AddCalendarOverrideUseCase",
    "AdminAuditLogModel",
    "Any",
    "ApplyPaymentWebhookUseCase",
    "ApprovePerformerServiceCommand",
    "ApprovePerformerServiceUseCase",
    "Argon2PasswordHasher",
    "AuthorizationError",
    "BootstrapAdminCommand",
    "BootstrapAdminUseCase",
    "BusinessSettingResponse",
    "CalculatePricePreviewCommand",
    "CalculatePricePreviewUseCase",
    "Callable",
    "CancelOrderCommand",
    "CancelOrderUseCase",
    "ConfirmReportCommand",
    "ConfirmReportUseCase",
    "CheckPerformerAvailabilityCommand",
    "CheckPerformerAvailabilityUseCase",
    "ComplaintModel",
    "ContactRequestModel",
    "DisputeModel",
    "ConflictError",
    "CreateCustomerAddressUseCase",
    "UpdateCustomerAddressCommand",
    "UpdateCustomerAddressUseCase",
    "CreateCustomerCareObjectCommand",
    "CreateCustomerCareObjectUseCase",
    "CreateDirectOrderCommand",
    "CreateDirectOrderUseCase",
    "CreateInvitationCommand",
    "CreateInvitationUseCase",
    "CreateManualRefundCommand",
    "CreateManualRefundUseCase",
    "CreateOwnerAddressCommand",
    "CreatePerformerAddressUseCase",
    "CreatePoolOrderCommand",
    "CreatePoolOrderUseCase",
    "CreateSystemCheckCommand",
    "CreateSystemCheckUseCase",
    "CustomerModel",
    "DaDataGeocoder",
    "Decimal",
    "DeleteCustomerAddressUseCase",
    "DeleteCustomerCareObjectUseCase",
    "DeletePerformerAddressUseCase",
    "FindSuitablePerformersCommand",
    "FindSuitablePerformersUseCase",
    "FinishOrderCommand",
    "FinishOrderUseCase",
    "GetCurrentAdminUseCase",
    "GetCustomerPaymentStatusCommand",
    "GetCustomerPaymentStatusUseCase",
    "GetCustomerProfileUseCase",
    "GetPerformerCalendarUseCase",
    "GetRegistrationStateUseCase",
    "InvalidOperation",
    "ListCustomerCareObjectsUseCase",
    "ListPerformerServicesUseCase",
    "LoginAdminCommand",
    "LoginAdminUseCase",
    "LogoutAdminUseCase",
    "NotFoundError",
    "NotificationModel",
    "OrderReportDetailDTO",
    "OrderReportFileDTO",
    "PaymentGatewayInitCommand",
    "PaymentGatewayRefundCommand",
    "PaymentWebhookCommand",
    "PerformerModel",
    "RedisAdminSessionStore",
    "RegisterCustomerCommand",
    "RegisterCustomerUseCase",
    "RegisterPerformerCommand",
    "RegisterPerformerUseCase",
    "RetryPaymentOperationCommand",
    "RetryPaymentOperationUseCase",
    "S3ObjectStorage",
    "SetPerformerAcceptingOrdersCommand",
    "SetPerformerAcceptingOrdersUseCase",
    "SetPerformerCurrentAddressUseCase",
    "SetPerformerScheduleCommand",
    "SetPerformerScheduleUseCase",
    "SetPerformerServiceEnabledCommand",
    "SetPerformerServiceEnabledUseCase",
    "SetPerformerServiceMaxObjectsCommand",
    "SetPerformerServiceMaxObjectsUseCase",
    "SqlAlchemyAddressRepository",
    "SqlAlchemyAdminAuditRepository",
    "SqlAlchemyAdminRepository",
    "SqlAlchemyAvailabilityRepository",
    "SqlAlchemyBusinessSettingRepository",
    "SqlAlchemyCareObjectRepository",
    "SqlAlchemyCatalogQueryService",
    "SqlAlchemyCustomerRepository",
    "SqlAlchemyFileRepository",
    "SqlAlchemyMatchingRepository",
    "SqlAlchemyMyOrdersQueryService",
    "SqlAlchemyNotificationRepository",
    "SqlAlchemyOrderRepository",
    "SqlAlchemyPaymentRepository",
    "SqlAlchemyPerformerRepository",
    "SqlAlchemyPricingRepository",
    "SqlAlchemySupportRepository",
    "SqlAlchemyUnitOfWork",
    "StartOrderCommand",
    "StartOrderByCustomerCommand",
    "StartOrderByCustomerUseCase",
    "StartOrderUseCase",
    "SubmitOrderReportCommand",
    "SubmitOrderReportUseCase",
    "SuggestAddressCommand",
    "SuggestAddressesUseCase",
    "SupportRequestModel",
    "TBankPaymentGateway",
    "TBankReceiptSettings",
    "TYPE_CHECKING",
    "UUID",
    "UpdateCustomerCareObjectCommand",
    "UpdateCustomerCareObjectUseCase",
    "UpdateCustomerUsernameCommand",
    "UpdateCustomerUsernameUseCase",
    "UpdateCustomerProfileCommand",
    "UpdateCustomerProfileUseCase",
    "UpdatePerformerUsernameCommand",
    "UpdatePerformerUsernameUseCase",
    "UploadPerformerAvatarCommand",
    "UploadPerformerAvatarUseCase",
    "ValidationError",
    "cast",
    "dataclass",
    "timedelta",
    "to_utc",
    "utc_now",
]
