FROM ghcr.io/astral-sh/uv:python3.14-alpine

WORKDIR /app
ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=0 \
    PATH="/app/.venv/bin:$PATH"

COPY pyproject.toml uv.lock README.md ./
COPY alembic.ini alembic.ini
COPY alembic alembic
COPY src src
COPY tests tests

RUN uv sync --frozen --all-groups
