from typing import Protocol


class UsernameSyncCache(Protocol):
    async def get(self, telegram_id: int) -> str | None: ...

    async def set(self, telegram_id: int, value: str, ttl_seconds: int) -> None: ...


class ActiveCategoryStore(Protocol):
    async def get(self, telegram_id: int) -> str | None: ...

    async def set(self, telegram_id: int, category_code: str) -> None: ...


class ScreenMessageStore(Protocol):
    async def get(self, telegram_id: int, screen_key: str) -> int | None: ...

    async def set(self, telegram_id: int, screen_key: str, message_id: int) -> None: ...

    async def delete(self, telegram_id: int, screen_key: str) -> None: ...
